"""agrege columna activo

Revision ID: 560c493d006a
Revises: b8c7f3d6f0b0
Create Date: 2024-01-26 21:00:10.312032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560c493d006a'
down_revision = 'b8c7f3d6f0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=True))
        batch_op.alter_column('sexo', server_default='NINGUNO')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
