"""removi not null tabla pedido

Revision ID: 97770775b4ac
Revises: ba87372d31cb
Create Date: 2024-02-07 20:04:51.523598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97770775b4ac'
down_revision = 'ba87372d31cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
